id = "comment"
name = "Comment"
version = "0.3.2"
schema_version = 1
authors = ["Donnie Adams <donnie@thedadams.com>"]
description = "Comment language extension"
repository = "https://github.com/thedadams/zed-comment"

[grammars.comment]
repository = "https://github.com/thedadams/tree-sitter-comment"
rev = "fe3651947a18db814c763244526d214e3c313cdf"
