id = "comment"
name = "Comments Highlighter"
version = "0.4.0"
schema_version = 1
authors = ["Donnie Adams <donnie@thedadams.com>"]
description = "Comment language extension for highlighting special comments"
repository = "https://github.com/thedadams/zed-comment"

[grammars.comment]
repository = "https://github.com/thedadams/tree-sitter-comment"
rev = "93b12e7b219d74fdbbb27e6671ca2f714738b253"
