id = "comment"
name = "Comments Highlighter"
version = "0.6.2"
schema_version = 1
authors = ["Donnie Adams <donnie@thedadams.com>"]
description = "Comment language extension for highlighting special comments"
repository = "https://github.com/thedadams/zed-comment"

[grammars.comment]
repository = "https://github.com/thedadams/tree-sitter-comment"
rev = "c16c22e4d72ece9a8c1da5a128fa20088e063275"
