id = "comment"
name = "Comments Highlighter"
version = "0.6.1"
schema_version = 1
authors = ["Donnie Adams <donnie@thedadams.com>"]
description = "Comment language extension for highlighting special comments"
repository = "https://github.com/thedadams/zed-comment"

[grammars.comment]
repository = "https://github.com/thedadams/tree-sitter-comment"
rev = "56771424c0026454360ac98b1bf8227a62714622"
