id = "comment"
name = "Comment"
version = "0.3.2"
schema_version = 1
authors = ["Donnie Adams <donnie@thedadams.com>"]
description = "Comment language extension"
repository = "https://github.com/thedadams/zed-comment"

[grammars.comment]
repository = "https://github.com/thedadams/tree-sitter-comment"
rev = "373c111834dca729b75ce9abb383a7f34bb2ae6c"
