id = "comment"
name = "Comments Highlighter"
version = "0.5.0"
schema_version = 1
authors = ["Donnie Adams <donnie@thedadams.com>"]
description = "Comment language extension for highlighting special comments"
repository = "https://github.com/thedadams/zed-comment"

[grammars.comment]
repository = "https://github.com/thedadams/tree-sitter-comment"
rev = "23fb30f2eac677f2afaa8556570ca6cd3493aa69"
